### ISSUE TITLE
"cannot load program: Operation not permitted" on Ubuntu Core 22

### ISSUE THREAD

**Issue by IsaacJT** [canonical/microceph#192]
I'm unable to get Microceph running on my ARM platform running Ubuntu Core 22. I'm running Microceph and snapd from the stable channel:

```
Name                              Version               Rev    Tracking            Publisher   Notes
core20                            20230801              2019   latest/stable       canonical✓  base
core22                            20230725              861    latest/stable       canonical✓  base
...
microceph                         0+git.02d9e5d         554    latest/stable       canonical✓  -
...
snapd                             2.60.2                19998  latest/stable       canonical✓  snapd
```

The board is an Orange Pi 5+ with a custom 5.10 kernel (as this is the latest kernel that Rockchip provides for the rk3588 platform). AppArmor and other snaps are working (including microk8s), but Microceph fails to start with the following snap log output:

```
2023-08-23T13:58:01Z systemd[1]: Started Service for snap application microceph.daemon.
2023-08-23T13:58:01Z microceph.daemon[69822]: cannot load program:
2023-08-23T13:58:01Z microceph.daemon[69822]: : Operation not permitted
2023-08-23T13:58:01Z systemd[1]: snap.microceph.daemon.service: Main process exited, code=exited, status=1/FAILURE
2023-08-23T13:58:01Z systemd[1]: snap.microceph.daemon.service: Failed with result 'exit-code'.
2023-08-23T13:58:01Z systemd[1]: snap.microceph.daemon.service: Scheduled restart job, restart counter is at 5.
2023-08-23T13:58:01Z systemd[1]: Stopped Service for snap application microceph.daemon.
2023-08-23T13:58:01Z systemd[1]: snap.microceph.daemon.service: Start request repeated too quickly.
2023-08-23T13:58:01Z systemd[1]: snap.microceph.daemon.service: Failed with result 'exit-code'.
2023-08-23T13:58:01Z systemd[1]: Failed to start Service for snap application microceph.daemon.
```

Unfortuantely it does not provide any additional debugging information, and there are no entries in dmesg regarding AppArmor denials. 

Is there a way to enable additional debug messages, or to somehow get more information on what's happening?

**Comment by IsaacJT** [comment]
It starts up in devmode, so there might be some AppArmor patches missing. Are there any specific AppArmor features that Microceph requires?

**Comment by UtkarshBhatthere** [comment]
Oh, there are no rule denials messages ?

**Comment by simondeziel** [comment]
If not apparmor (no denial logs), it could be a seccomp policy issue.

**Comment by lmlg** [comment]
I could not reproduce this on a virtual machine using ARM64:

```
lmlg@debian:~$ uname -a
Linux debian 6.1.0-11-arm64 #1 SMP Debian 6.1.38-4 (2023-08-08) aarch64 GNU/Linux

lmlg@debian:~$ microceph.ceph status
  cluster:
    id:     3967ad48-9a36-4a0b-b636-5bafbf1dfed1
    health: HEALTH_OK
 
  services:
    mon: 1 daemons, quorum debian (age 59s)
    mgr: no daemons active
    osd: 0 osds: 0 up, 0 in
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   0 B used, 0 B / 0 B avail
    pgs: 
```

Here are the apparmor rules:

```
lmlg@debian:~$ sudo aa-status | grep microceph
   snap-update-ns.microceph
   snap.microceph.ceph
   snap.microceph.daemon
   snap.microceph.hook.install
   snap.microceph.hook.post-refresh
   snap.microceph.mds
   snap.microceph.mgr
   snap.microceph.microceph
   snap.microceph.mon
   snap.microceph.osd
   snap.microceph.rados
   snap.microceph.radosgw-admin
   snap.microceph.rbd
   snap.microceph.rgw
   /snap/microceph/554/bin/microcephd (1160) snap.microceph.daemon
   /snap/microceph/554/bin/ceph-mds (1653) snap.microceph.mds
   /snap/microceph/554/bin/ceph-mgr (1562) snap.microceph.mgr
   /snap/microceph/554/bin/ceph-mon (1451) snap.microceph.mon
   /usr/bin/dash (1807) snap.microceph.osd
   /usr/bin/sleep (1833) snap.microceph.osd
```

It appears you're missing some rules for the ceph daemons?
