### ISSUE TITLE
microceph cluster forms with 4 active monitors

### ISSUE THREAD

**Issue by javacruft** [canonical/microceph#351]
# Issue report

## What version of MicroCeph are you using ?

reef/candidate

## What are the steps to reproduce this issue ?

See https://bugs.launchpad.net/charm-microceph/+bug/2066392

## What happens (observed behaviour) ?

Ceph cluster bootstraps with 4 monitors active.

## What were you expecting to happen ?

Only three should be active.

**Comment by sabaini** [comment]
While this can be easily reproed with charm-microceph (cf. https://bugs.launchpad.net/charm-microceph/+bug/2066392) I could not immediately repro this issue with a non-charmed microceph cluster

This would hint at a charm-microceph specific issue (possibly timing/race?)

```
juju ssh 0 -- sudo microceph status
MicroCeph deployment summary:
- juju-887f77-mc-0 (172.20.0.250)
  Services: mds, mgr, mon
  Disks: 0
- juju-887f77-mc-1 (172.20.0.230)
  Services: 
  Disks: 0
- juju-887f77-mc-2 (172.20.0.62)
  Services: mds, mgr, mon
  Disks: 0
- juju-887f77-mc-3 (172.20.0.157)
  Services: mds, mgr, mon
  Disks: 0
```
