### ISSUE TITLE
[question] microceph as lxc

### ISSUE THREAD

**Issue by TorbenMartin** [canonical/microceph#566]
hello.

https://blog.ovhcloud.com/journey-to-next-gen-ceph-storage-at-ovhcloud-with-lxd/

i never success this with cephadm ceph. wasted a lot time of my life.
but today it success with microceph. **is this recommend with enough baremetal servers and physical disks in a production setup**?

in my example i use zfs volumes.

```
#simulate different block devices
zfs create -s -V 50G storage/vol1
zfs create -s -V 50G storage/vol2
zfs create -s -V 50G storage/vol3
zfs create -s -V 50G storage/vol4
zfs create -s -V 50G storage/vol5

lxc init ubuntu:24.04 ct1 -p default
lxc init ubuntu:24.04 ct2 -p default
lxc init ubuntu:24.04 ct3 -p default
lxc init ubuntu:24.04 ct4 -p default
lxc init ubuntu:24.04 ct5 -p default

lxc config device add ct1 volume1 unix-block source=/dev/zvol/storage/vol1 path=/dev/sdb
lxc config device add ct2 volume1 unix-block source=/dev/zvol/storage/vol2 path=/dev/sdb
lxc config device add ct3 volume1 unix-block source=/dev/zvol/storage/vol3 path=/dev/sdb
lxc config device add ct4 volume1 unix-block source=/dev/zvol/storage/vol4 path=/dev/sdb
lxc config device add ct5 volume1 unix-block source=/dev/zvol/storage/vol5 path=/dev/sdb

lxc start ct1 ct2 ct3 ct4 ct5


snap install microceph --channel=squid/stable
snap refresh --hold microceph
snap connect microceph:dm-crypt
snap restart microceph.daemon

#first node!!!
microceph cluster bootstrap
microceph disk add /dev/sdb

microceph cluster add ct2
microceph cluster add ct3
microceph cluster add ct4
microceph cluster add ct5

#all other ct
microceph cluster join <TOKEN>
microceph disk add /dev/sdb

microceph status
```

```
root@ct1:~# microceph status
MicroCeph deployment summary:
- ct1 (10.0.1.24)
  Services: mds, mgr, mon, osd
  Disks: 1
- ct2 (10.0.1.204)
  Services: mds, mgr, mon, osd
  Disks: 1
- ct3 (10.0.1.42)
  Services: mds, mgr, mon, osd
  Disks: 1
- ct4 (10.0.1.226)
  Services: osd
  Disks: 1
- ct5 (10.0.1.252)
  Services: osd
  Disks: 1
root@ct1:~# microceph status
MicroCeph deployment summary:
- ct1 (10.0.1.24)
  Services: mds, mgr, mon, osd
  Disks: 1
- ct2 (10.0.1.204)
  Services: mds, mgr, mon, osd
  Disks: 1
- ct3 (10.0.1.42)
  Services: mds, mgr, mon, osd
  Disks: 1
- ct4 (10.0.1.226)
  Services: osd
  Disks: 1
- ct5 (10.0.1.252)
  Services: osd
  Disks: 1
root@ct1:~# ceph -s
  cluster:
    id:     6d306ce7-4427-4756-bdc9-17072c830bf1
    health: HEALTH_OK
 
  services:
    mon: 3 daemons, quorum ct1,ct2,ct3 (age 74s)
    mgr: ct1(active, since 14m), standbys: ct2, ct3
    osd: 4 osds: 3 up (since 3s), 4 in (since 4s)
 
  data:
    pools:   0 pools, 0 pgs
    objects: 0 objects, 0 B
    usage:   479 MiB used, 150 GiB / 150 GiB avail
    pgs: 
```

```
ceph osd crush add-bucket dc1 root

ceph osd crush add-bucket rack1 rack
ceph osd crush add-bucket rack2 rack
ceph osd crush add-bucket rack3 rack
ceph osd crush move rack1 root=dc1
ceph osd crush move rack2 root=dc1
ceph osd crush move rack3 root=dc1

ceph osd crush move ct1 rack=rack1
ceph osd crush move ct2 rack=rack1
ceph osd crush move ct3 rack=rack2
ceph osd crush move ct4 rack=rack3
ceph osd crush move ct5 rack=rack3


root@ct1:~# ceph osd crush tree
ID   CLASS  WEIGHT   TYPE NAME        
 -7         0.24399  root dc1         
 -8         0.09760      rack rack1   
 -2         0.04880          host ct1 
  1         0.04880              osd.1
 -3         0.04880          host ct2 
  2         0.04880              osd.2
 -9         0.04880      rack rack2   
 -4         0.04880          host ct3 
  3         0.04880              osd.3
-10         0.09760      rack rack3   
 -5         0.04880          host ct4 
  4         0.04880              osd.4
 -6         0.04880          host ct5 
  5         0.04880              osd.5
 -1               0  root default  




ceph osd crush rule ls
ceph osd crush rule create-replicated replicated_rule_rack dc1 rack


root@ct1:~# ceph osd crush rule dump replicated_rule_rack
{
    "rule_id": 3,
    "rule_name": "replicated_rule_rack",
    "type": 1,
    "steps": [
        {
            "op": "take",
            "item": -7,
            "item_name": "dc1"
        },
        {
            "op": "chooseleaf_firstn",
            "num": 0,
            "type": "rack"
        },
        {
            "op": "emit"
        }
    ]
}
```
